import Head from "next/head";
import { Inter } from "next/font/google";
import Navbar from "../../Components/Home/Navbar";
import Hero from "../../Components/Home/Hero";
import Mentions from "../../Components/Home/Mentions";
import Footer from "../../Components/Home/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Hyperglot Journal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <Navbar />
      <Hero />
      <Mentions />
      <Footer />
      </main>
    </>
  );
}
